"""Streamlit chat demo against the FastAPI /ask endpoint.

Run:  uv run --group demo streamlit run demo/app.py
Needs the API up (docker compose up -d) and Ollama running.
"""

import json
import os

import httpx
import streamlit as st

API = os.environ.get("RAG_API", "http://localhost:8000")

EXAMPLES = [
    "Does comprehensive cover hitting a deer?",
    "What are the Texas minimum liability limits?",
    "Does my policy cover my boat?",
]

st.set_page_config(page_title="Auto Insurance RAG", page_icon=None, layout="centered")
st.markdown(
    "<style>div[data-testid='stButton'] button {font-size: 0.85rem; padding: 2px 10px;}</style>",
    unsafe_allow_html=True,
)

st.markdown("### Auto Insurance RAG")
st.markdown("Local, cited, eval-gated — answers only from the ingested corpus.")
st.caption(
    "[GitHub](https://github.com/VasanthPrabahar/rag-insurance) · "
    "recall@5 0.769 · 29/29 citations verified · runs fully local"
)

with st.sidebar:
    st.header("Engine")
    engine = st.radio(
        "Engine",
        ["pipeline", "agent"],
        label_visibility="collapsed",
        captions=[
            "Fastest for normal questions.",
            "Adds a router that refuses off-topic questions in ~1s.",
        ],
    )
    st.header("State filter")
    state = st.selectbox(
        "State filter",
        ["auto-detect", "TX", "CA", "AZ", "NV", "VA"],
        label_visibility="collapsed",
        help="auto-detect scopes retrieval to a state only when the question names one.",
    )
    with st.expander("About", expanded=False):
        st.markdown(
            "Hybrid retrieval (dense + BM25 with RRF) over state insurance "
            "documents in pgvector, with policy-register query expansion. "
            "Answers are generated by a local llama3.1:8b and every citation "
            "is mechanically verified against the retrieved chunks. "
            "Out-of-scope questions get an honest refusal, not a guess."
        )

if "messages" not in st.session_state:
    st.session_state.messages = []

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        if message.get("refused"):
            st.info(message["content"])
        else:
            st.markdown(message["content"])
        for source in message.get("sources", []):
            with st.expander(source["label"]):
                st.text(source["text"])


def sse_events(response):
    event = None
    for line in response.iter_lines():
        if line.startswith("event: "):
            event = line.removeprefix("event: ")
        elif line.startswith("data: "):
            yield event, json.loads(line.removeprefix("data: "))


question = None
if not st.session_state.messages:
    columns = st.columns(len(EXAMPLES))
    for column, example in zip(columns, EXAMPLES, strict=True):
        if column.button(example):
            question = example
question = st.chat_input("Ask about auto insurance…") or question

if question:
    st.session_state.messages.append({"role": "user", "content": question})
    with st.chat_message("user"):
        st.markdown(question)

    payload = {
        "question": question,
        "engine": {"mode": engine},
        "filters": {"state": None if state == "auto-detect" else state},
    }
    with st.chat_message("assistant"):
        placeholder = st.empty()
        streamed, final = "", None
        try:
            with st.status("Searching the corpus…") as status:
                stream = httpx.stream("POST", f"{API}/ask", json=payload, timeout=300.0)
                with stream as response:
                    for event, data in sse_events(response):
                        if status is not None:
                            status.update(label="Generating…", state="complete", expanded=False)
                            status = None
                        if event == "token":
                            streamed += data["text"]
                            placeholder.markdown(streamed + "▌")
                        elif event == "final":
                            final = data
        except httpx.ConnectError:
            st.error(f"API unreachable at {API}. Start the stack: `docker compose up -d`")
            st.stop()

        answer = final["answer"] if final else streamed
        refused = bool(final and final["refused"])
        if refused:
            placeholder.empty()
            st.info(answer)
        else:
            placeholder.markdown(answer)

        sources = []
        if final:
            by_id = {c["chunk_id"]: c for c in final["retrieved"]}
            for citation in final["citations"]:
                chunk = by_id.get(citation["chunk_id"], {})
                label = (
                    f"[{citation['chunk_id']}] {citation['doc_name']} "
                    f"› chunk {citation['chunk_index']}"
                )
                sources.append({"label": label, "text": chunk.get("content", "")})
            latency = final["latency"]
            st.caption(
                f"{engine} · expand {latency['expand_ms']:.0f} ms · "
                f"retrieve {latency['retrieve_ms']:.0f} ms · "
                f"generate {latency['generate_ms']:.0f} ms · "
                f"total {latency['total_ms'] / 1000:.1f} s"
            )
        for source in sources:
            with st.expander(source["label"]):
                st.text(source["text"])

    st.session_state.messages.append(
        {"role": "assistant", "content": answer, "sources": sources, "refused": refused}
    )
